### ISSUE TITLE
Just a suggestion

### ISSUE THREAD

**Issue by poa00** [Asteski/WinMac#11]
I actually already have most of these tools installed, so I'm not using WinMac personally, but I have friends that are and it's really sweet. 

Just thought I'd offer a friendly suggestion:  To give the user a more 'unix-like / linux experience', you might offer to install `WSL` as part of the Terminal customizations.  It is, after all -- at least WSL v1 -- a terminal-hosted feature (mostly).

**Comment by Asteski** [comment]
Hello,

Thanks for kind words, but the reason I don't want to implement WSL is it's because it enforces runnign two os at the same time, consuming a lot of memory/cpu, and it makes interacting with Windows quite limited, hence I don't want to implemnt in a way, that any WinMac component would be dependent on it. It also depends on virtualization being possible/enabled on specific pc, and that creates another hoops to jumo through, I'd need to spend a lot ot time fixing. WSL is definitely something I can recommend for sure, but I want to close WinMac experience within Windows as much as possible.

**Comment by poa00** [comment]
Ahh understood
